# Generated by Django 4.1.5 on 2023-01-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_loginhistory_login_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='login_date_time',
            field=models.DateTimeField(),
        ),
    ]
